name: eisenhower_matrix
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  radio_grouped_buttons: ^1.0.1
  another_flushbar: ^1.12.30
  get_it: ^7.6.0
  lottie: ^2.5.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/img/
   - assets/lottie/


flutter_intl:
  enabled: true